web:
    image: wordpress
    links:
     - mysql
    environment:
     - WORDPRESS_DB_PASSWORD=password
    ports:
     - "127.0.10.2:8080:80"
    working_dir: /var/www/html
    volumes:
     - /home/alberto/contenedores-vms/practica/docker-compose/wordpress/wp-content/:/var/www/html/wp-content
mysql:
    image: mysql:5.7
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=wordpress
